### ISSUE TITLE
Consider "dev-master" as dependencies in the master-branch

### ISSUE THREAD

**Issue by neufeind** [Nimut/typo3-complete#2]
When trying to require the dev-master-Version of this package it still tries to load 9.4.0 of all dependent packages (as is obvious). Would it make sense / be viable to have the master always have dependencies "dev-master" maybe? But to be able to go from 9.4.0 to 9.5.0 we'd then need a branch where you could add a commit for 9.5.0 and from there add the tag 9.5.0?

**Comment by IchHabRecht** [comment]
HI @neufeind,

Thank you for the issue. Having the master on the tag was a fault from last build. I reset the master to dev-master. Everything should now work as expected.

**Comment by neufeind** [comment]
Thanks for the quick feedback.
